# aicryptopredictor/prometheus.yml
scrape_configs:
  - job_name: 'aicryptopredictor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['aicryptopredictor.com']
    scheme: 'https'
    scrape_interval: 15s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: aicryptopredictor.com:443