scrape_configs:
  - job_name: 'trading-calculator-web3'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['web3.tradingpositionsizecalculator.com']
    scheme: 'https'
    scrape_interval: 15s