global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: 'aicryptopredictor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['aicryptopredictor.com']
    scheme: 'https'
    scrape_interval: 15s

  - job_name: 'trading-calculator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tradingpositionsizecalculator.com']
    scheme: 'https'

  - job_name: 'trading-calculator-web3'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['web3.tradingpositionsizecalculator.com']
    scheme: 'https'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']