scrape_configs:
  - job_name: 'trading-calculator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tradingpositionsizecalculator.com']
    scheme: 'https'
    scrape_interval: 30s